default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  port: 5432
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: debugrepo_development

test:
  <<: *default
  database: debugrepo_test

production:
  <<: *default
  database: debugrepo_production
  username: debugrepo
  password: <%= ENV["DEBUGREPO_DATABASE_PASSWORD"] %>
